name: dinder
description: A dating app for dogs only, which can help you to choose what breed they want to choose for your own pet. 
  Using flutter as the framework to build Dinder on multi-platform from a single codebase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Stacked Architecture
  stacked: ^2.3.8
  stacked_services: ^0.8.24

  # Data Models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

  # Utilities
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  stacked_generator: ^0.8.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/